#!/bin/bash

source "$UTILS_PROJECT_PATH"/BASHRC/common_bashrc
source "$UTILS_PROJECT_PATH"/BASHRC/git
source "$UTILS_PROJECT_PATH"/BASHRC/nerdtree_for_ror
source "$UTILS_PROJECT_PATH"/BASHRC/ruby_and_rails
source "$UTILS_PROJECT_PATH"/BASHRC/group_buddies

# Commun bash usage
alias update="sudo aptitude update"
alias install="sudo aptitude install"
alias upgrade="sudo aptitude safe-upgrade"
alias remove="sudo aptitude remove"

