#!/bin/bash

source "$UTILS_PROJECT_PATH"/BASHRC/common_bashrc
source "$UTILS_PROJECT_PATH"/BASHRC/git
source "$UTILS_PROJECT_PATH"/BASHRC/nerdtree_for_ror
source "$UTILS_PROJECT_PATH"/BASHRC/ruby_and_rails
