#!/bin/bash

# Commun bash usage
alias utils-menu="bash $UTILS_PROJECT_PATH/BASH_SCRIPTS/utils_menu.sh"
alias silver_backup="bash $UTILS_PROJECT_PATH/BASH_SCRIPTS/silver_backup.sh"
alias killit="bash $UTILS_PROJECT_PATH/BASH_SCRIPTS/killit.sh"
alias free="free -m"
alias update="sudo aptitude update"
alias install="sudo aptitude install"
alias upgrade="sudo aptitude safe-upgrade"
alias remove="sudo aptitude remove"
alias l="ls -an"
alias up="cd .."
alias up1="cd .."
alias up2="cd ../.."
alias up3="cd ../../.."
alias up4="cd ../../../.."
alias up5="cd ../../../../.."
alias up6="cd ../../../../../.."
export PATH=.:$PATH

# Ruby
alias geminstall="sudo gem install --no-ri --no-rdoc"

# Git Alias
alias gst='git status'
alias gl='git pull'
alias gp='git push'
alias gd='git diff | mate'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gb='git branch'
alias gba='git branch -a'

# Ruby on Rails
function db_reborn {
	LOWER_RAILS_ENV=$(tr [:upper:] [:lower:] <<< "$RAILS_ENV")
	if [ "$LOWER_RAILS_ENV" == "production" ]; then
		echo "WARNING: You are trying to db_reborn in a PRODUCTION SERVER."
		echo "This will COMPLETELY ERASE this application's DATABASE!!!"
		read -p "Do you really want to do it? [y/N] "
		if [[ "$REPLY" == "y" || "$REPLY" == "Y" ]]; then
			rake db:migrate:reset && rake db:seed && rake db:test:clone && rm -r public/system ; mkdir -p public/system
		else
			echo "Aborted db_reborn"
		fi
	fi
}

function ultimate_reborn {
	LOWER_RAILS_ENV=$(tr [:upper:] [:lower:] <<< "$RAILS_ENV")
	if [ "$LOWER_RAILS_ENV" == "production" ]; then
		echo "WARNING: You are trying to ultimate_reborn in a PRODUCTION SERVER."
		echo "This will COMPLETELY ERASE this application's DATABASE!!!"
		read -p "Do you really want to do it? [y/N] "
		if [[ "$REPLY" == "y" || "$REPLY" == "Y" ]]; then
			ss_stop ; rake db:migrate:reset && rake db:seed && ruby script/server -d && rake jobs:work
		else
			echo "Aborted ultimate_reborn"
		fi
	fi
}

# Deprecated
# alias db_reborn="rake db:migrate:reset && rake db:seed && rake db:test:clone && rm -r public/system ; mkdir public/system"
# alias ultimate_reborn='ss_stop ; rake db:migrate:reset && rake db:seed && ruby script/server -d && rake jobs:work'

alias ss_stop='kill -9 $(ps -A n | grep "[^]] ruby script/server" | egrep "^\s*[0-9]+" -o)'
alias reset_application='rm -rf public/javascripts/cache/ ; rm -rf public/stylesheets/cache/ ; touch tmp/restart.txt ; compass ; rake themes:choose'
alias rjw="rake jobs:work"
alias ss="ruby script/server start"
alias sc="ruby script/console"
prepare_NERDTree_for_rails() {
  #if self.isSymLink && !(b:NERDTreeRoot.path.pathSegments[-1] =~ 'Project_NERDTree')
  rm -rf tmp/Project_NERDTree
  mkdir tmp/Project_NERDTree
  ln -s ../../app/models/           tmp/Project_NERDTree/01-Models
  ln -s ../../app/views/            tmp/Project_NERDTree/02-Views
  ln -s ../../app/controllers/      tmp/Project_NERDTree/03-Controllers
  ln -s ../../app/helpers/          tmp/Project_NERDTree/04-Helpers
  ln -s ../../features/             tmp/Project_NERDTree/05-Features
  ln -s ../../test/                 tmp/Project_NERDTree/06-Test
  ln -s ../../db/migrate            tmp/Project_NERDTree/08-Migrations
  ln -s ../../public/stylesheets    tmp/Project_NERDTree/08-Stylesheets
  ln -s ../../public/javascripts    tmp/Project_NERDTree/09-Javascripts
  ln -s ../../config/               tmp/Project_NERDTree/10-Config
  ln -s ../../                      tmp/Project_NERDTree/11-Root
}
et() {
  prepare_NERDTree_for_rails
  vim "+NERDTree tmp/Project_NERDTree" "+nnoremap <buffer> <silent> <space>  \|:silent exec 'vertical resize '.(match(g:proj_flags, '\Ct')!=-1 && winwidth('.') > 20? (20) : (winwidth('.') + 100))<CR>" "+exec 'vertical resize'.20" config/routes.rb
}
vet() {
  prepare_NERDTree_for_rails
  gvim "+NERDTree tmp/Project_NERDTree" "+nnoremap <buffer> <silent> <space>  \|:silent exec 'vertical resize '.(match(g:proj_flags, '\Ct')!=-1 && winwidth('.') > 20? (20) : (winwidth('.') + 100))<CR>" "+exec 'vertical resize'.20" config/routes.rb
}
rails_environment_chooser() {
  echo "The current Rails Environment is $RAILS_ENV."
  echo "1 - Development"
  echo "2 - Test"
  echo "3 - Production"
  echo "4 - Reset RAILS_ENV"
  echo "Chose the new environment option:"
  read -n1 KEY
  echo ""
  case "$KEY" in
    "1" ) export RAILS_ENV='development';;
    "2" ) export RAILS_ENV='test';;
    "3" ) export RAILS_ENV='production';;
    "4" ) unset  RAILS_ENV;;
    *   )
      echo "Wrong option!"
      return 1
    ;;
  esac
  echo "RAILS_ENV have been setted to $RAILS_ENV."
}  

# Git
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1]/'
}
 # Usage Exampe: 
 # export PS1='\[\033[0;35m\]\h \[\033[0;33m\]\w\[\033[0;32m\] $(parse_git_branch)\[\033[00m\]: '
 # if you want to change this line you should think in changing the install file too.
