#!/bin/bash

# Commun bash usage
alias free="free -m"
alias l="ls -an"
alias up="cd .."
alias up1="cd .."
alias up2="cd ../.."
alias up3="cd ../../.."
alias up4="cd ../../../.."
alias up5="cd ../../../../.."
alias up6="cd ../../../../../.."
export PATH=.:$PATH
