#!/bin/bash

# Commun bash usage
alias dirmenu="$UTILS_PROJECT_PATH/Menu/dirmenu"
alias utils-menu="dirmenu $UTILS_PROJECT_PATH/Menu/utils-menu"

alias free="free -m"
alias l="ls -an"
alias up="cd .."
alias up1="cd .."
alias up2="cd ../.."
alias up3="cd ../../.."
alias up4="cd ../../../.."
alias up5="cd ../../../../.."
alias up6="cd ../../../../../.."
export PATH=.:$PATH