#!/bin/bash

# Git Alias
alias gst='git status'
alias gl='git pull'
alias gp='git push'
alias gd='git diff | mate'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gb='git branch'
alias gba='git branch -a'

# Git
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1]/'
}
 # Usage Exampe: 
 # export PS1='\[\033[0;35m\]\h \[\033[0;33m\]\w\[\033[0;32m\] $(parse_git_branch)\[\033[00m\]: '
 # if you want to change this line you should think in changing the install file too.
